### ISSUE TITLE
Error with NERDTree when switching projects

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [dbakker/vim-projectroot#13]
I do the following:
1. I open a file in one project
2. I Open NERDTree with ":NERDTreeFind"
3. I Open a file from another project
4. I call ":NERDTreeFind" again

Then I get this error:

```
Error detected while processing function <SNR>29_findAndRevealPath:
line   33:
E716: Key not present in Dictionary: setShowHidden
```

The error does not occure, if vim-projectroot is not installed

**Comment by dbakker** [comment]
Sorry, for the late response. I haven't been able to reproduce the error yet. Have you tried it with an empty vimrc with just nerdtree and projectroot?
