### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by sbosnick1** [dbakker/vim-projectroot#15]
The project and the files it contains do not make any mention of the terms under which they are licensed. This makes it legally difficult to copy the code for new project as is suggested in the documentation. You could consider adding a license section to the README.md file that says "Copyright (c) Daan Bakker. Distributed under the same terms as Vim itself. See :help license." if you wanted to use Vim license. This is how Tim Pope does it (see, for example, https://github.com/tpope/vim-pathogen/blob/master/README.markdown).

**Comment by dbakker** [comment]
Good point, thank you.
